################################################################################
#                                                                              #
#           https://github.com/leukipp/cortile/blob/main/config.toml           #
#                                                                              #
################################################################################

#################################### Tiling ####################################

# Tiling will be enabled on application start if set to true (true | false).
tiling_enabled = true

# Initial tiling layout ("fullscreen" | "vertical-left" | "vertical-right" | "horizontal-top" | "horizontal-bottom").
tiling_layout = "vertical-right"

# An overlay window is displayed for this time period when the layout was changed (0ms = disabled).
tiling_gui = 1500

#################################### Window ####################################

# Regex RE2 syntax to ignore windows (WM_CLASS string can be found by running 'xprop WM_CLASS').
# window_ignore = [
#   ['WM_CLASS', 'WM_NAME'] = ['ignore all windows with this class', 'but allow those with this name']
# ]
window_ignore = [
    ['nm.*', ''],
    ['gcr.*', ''],
    ['polkit.*', ''],
    ['wrapper.*', ''],
    ['lightdm.*', ''],
    ['blueman.*', ''],
    ['pavucontrol.*', ''],
    ['firefox.*', '.*Mozilla Firefox'],
]

# Maximum number of allowed master windows (0 - 10).
window_masters_max = 5

# Maximum number of allowed slave windows (1 - 10).
window_slaves_max = 5

# How much space should be left between windows (0 - 100).
window_gap_size = 4

# Window decorations will be removed if set to false (true | false).
window_decoration = true

################################## Proportion ##################################

# Initial division of master-slave area (0.0 - 1.0).
proportion = 0.6

# Minimum division of master-slave area (0.0 - 1.0).
proportion_min = 0.1

# Maximum division of master-slave area (0.0 - 1.0).
proportion_max = 0.9

# How much to increment/decrement master-slave area (0.0 - 1.0).
proportion_step = 0.05

##################################### Edge #####################################

# Additional margin of the tiling area ([top, right, bottom, left]).
edge_margin = [0, 0, 0, 0]

# Width and height of a hot-corner area within the edge corners (0 - 100).
edge_corner_size = 10

# Width or height of a hot-corner area within the edge centers (0 - 100).
edge_center_size = 100

################################################################################
[colors]                            # RGBA color values used for gui elements. #
################################################################################

# Layout window text color.
gui_text = [255, 255, 255, 255]

# Layout window background color.
gui_background = [30, 30, 40, 255]

# Layout slave client rectangle color.
gui_client_slave = [58, 58, 78, 255]

# Layout master client rectangle color.
gui_client_master = [98, 98, 128, 255]

################################################################################
[keys]                            # Key symbols can be found by running 'xev'. #
################################################################################

# Tile the current workspace.
tile = "Control-Shift-T"

# Untile the current workspace.
untile = "Control-Shift-U"

# Cycles through the available layouts.
layout_cycle = "Control-Shift-L"

# Activates the fullscreen layout.
layout_fullscreen = "Control-Shift-Space"

# Activates the vertical-left layout.
layout_vertical_left = "Control-Shift-Left"

# Activates the vertical-right layout.
layout_vertical_right = "Control-Shift-Right"

# Activates the horizontal-top layout.
layout_horizontal_top = "Control-Shift-Up"

# Activates the horizontal-bottom layout.
layout_horizontal_bottom = "Control-Shift-Down"

# Make the active window as master.
master_make = "Control-Shift-M"

# Increase the number of masters.
master_increase = "Control-Shift-Plus"

# Decrease the number of masters.
master_decrease = "Control-Shift-Minus"

# Increase the number of slaves.
slave_increase = "Control-Shift-KP_Add"

# Decrease the number of slaves.
slave_decrease = "Control-Shift-KP_Subtract"

# Increase the proportion of master-slave area.
proportion_increase = "Control-Shift-KP_6"

# Decrease the proportion of master-slave area.
proportion_decrease = "Control-Shift-KP_4"

# Moves focus to the next window.
window_next = "Control-Shift-KP_2"

# Moves focus to the previous window.
window_previous = "Control-Shift-KP_8"

################################################################################
[corners]                    # Action strings from above or external commands. #
################################################################################

# Corner at top left.
top_left = "window_previous"

# Corner at top center.
top_center = "layout_horizontal_top"

# Corner at top right.
top_right = "master_make"

# Corner at center right.
center_right = "layout_vertical_right"

# Corner at bottom right.
bottom_right = "proportion_increase"

# Corner at bottom center.
bottom_center = "layout_horizontal_bottom"

# Corner at bottom left.
bottom_left = "proportion_decrease"

# Corner at center left.
center_left = "layout_vertical_left"
