############################################################
# https://github.com/leukipp/cortile/blob/main/config.toml #
############################################################

# Tiling will be enabled on application start if set to true (true | false).
tiling_enabled = true

# Initial tiling layout ("vertical" | "horizontal" | "fullscreen").
tiling_layout = "vertical"

# Initial division of master-slave area (0.0 - 1.0).
proportion = 0.6

# Minimum division of master-slave area (0.0 - 1.0).
proportion_min = 0.1

# Maximum division of master-slave area (0.0 - 1.0).
proportion_max = 0.9

# How much to increment/decrement master-slave area (0.0 - 1.0).
proportion_step = 0.05

# How much space should be left between windows (0 - 100).
window_gap = 4

# Window decorations will be removed if set to false (true | false).
window_decoration = true

# Regex in RE2 syntax for ignoring windows (['WM_CLASS', 'WM_NAME'] = ['ignore all windows with this class', 'but allow those with this name']).
# WM_CLASS string can be found by running 'xprop WM_CLASS'.
window_ignore = [
    ['nm.*', ''],
    ['gcr.*', ''],
    ['polkit.*', ''],
    ['wrapper.*', ''],
    ['lightdm.*', ''],
    ['blueman.*', ''],
    ['pavucontrol.*', ''],
    ['xfce4-display-settings.*', ''],
    ['firefox.*', '.*Mozilla Firefox'],
]


############################################################
[keys]        # Key symbols can be found by running 'xev'. #
############################################################

# Tile the current workspace.
tile = "control-shift-t"

# Untile the current workspace.
untile = "control-shift-u"

# Cycles through the available layouts.
layout_cycle = "control-shift-c"

# Activates the vertical layout.
layout_vertical = "control-shift-v"

# Activates the horizontal layout.
layout_horizontal = "control-shift-h"

# Activates the fullscreen layout.
layout_fullscreen = "control-shift-f"

# Make the active window as master.
master_make = "control-shift-m"

# Increase the number of masters.
master_increase = "control-shift-i"

# Decrease the number of masters.
master_decrease = "control-shift-d"

# Increases the size of the master windows.
proportion_increase = "control-shift-plus"

# Decreases the size of the master windows.
proportion_decrease = "control-shift-minus"

# Moves focus to the next window.
window_next = "control-shift-right"

# Moves focus to the previous window.
window_previous = "control-shift-left"


############################################################
[corners]  # Action strings can also be external commands. #
############################################################

# Corner at top left
top_left = "layout_cycle"

# Corner at top center
top_center = "tile"

# Corner at top right
top_right = "master_make"

# Corner at center right
center_right = "proportion_increase"

# Corner at bottom right
bottom_right = "master_increase"

# Corner at bottom center
bottom_center = "untile"

# Corner at bottom left
bottom_left = "master_decrease"

# Corner at center left
center_left = "proportion_decrease"
