name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Run releaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        goos:
          - linux
        goarch:
          - amd64
          - arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
